<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>unitree_ros2</name>
  <version>0.0.1</version>
  <description>Unitree GO2 ROS2 Package for SLAM and Navigation</description>
  <maintainer email="koumapierre10@gmail.com">Pierre</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rtabmap_ros</exec_depend>
  <exec_depend>rtabmap_viz</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
